- name: Clone OpenLane
  run: |
    git clone https://github.com/The-OpenROAD-Project/OpenLane.git
    cd OpenLane
    make

- name: Run OpenLane Flow
  run: |
    cd OpenLane
    make mount
    ./flow.tcl -design ../designs/timer_peripheral
