name: OpenLane ASIC Flow

on:
  push:
    branches: [ "main" ]

jobs:
  openlane:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run OpenLane Flow
        uses: The-OpenROAD-Project/OpenLane@master
        with:
          design-dir: designs
          design-name: timer_peripheral
