name: OpenLane ASIC Flow

on:
  push:
    branches:
      - main

jobs:
  openlane:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone OpenLane
        run: |
          git clone https://github.com/The-OpenROAD-Project/OpenLane.git
          cd OpenLane
          make

      - name: Run OpenLane Flow
        run: |
          cd OpenLane
          make mount
          ./flow.tcl -design ../designs/timer_peripheral
