name: OpenLane ASIC Flow

on:
  push:
    branches: [ "main" ]

jobs:
  openlane:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull OpenLane Docker image
        run: docker pull efabless/openlane:latest

      - name: Run OpenLane RTL to GDS
        run: |
          docker run --rm \
            -v $PWD:/work \
            efabless/openlane:latest \
            /openlane/flow.tcl \
            -design /work/designs/timer_peripheral \
            -tag run1
